#pragma once
#include "Definitions.h"

#pragma region Enums
enum ReanimationType
{
	REANIM_NONE = 0xFFFFFFFF,
	REANIM_LOADBAR_SPROUT = 0x0,
	REANIM_LOADBAR_ZOMBIEHEAD = 0x1,
	REANIM_SODROLL = 0x2,
	REANIM_FINAL_WAVE = 0x3,
	REANIM_PEASHOOTER = 0x4,
	REANIM_WALLNUT = 0x5,
	REANIM_LILYPAD = 0x6,
	REANIM_SUNFLOWER = 0x7,
	REANIM_LAWNMOWER = 0x8,
	REANIM_READYSETPLANT = 0x9,
	REANIM_CHERRYBOMB = 0xA,
	REANIM_SQUASH = 0xB,
	REANIM_DOOMSHROOM = 0xC,
	REANIM_SNOWPEA = 0xD,
	REANIM_REPEATER = 0xE,
	REANIM_SUNSHROOM = 0xF,
	REANIM_TALLNUT = 0x10,
	REANIM_FUMESHROOM = 0x11,
	REANIM_PUFFSHROOM = 0x12,
	REANIM_HYPNOSHROOM = 0x13,
	REANIM_CHOMPER = 0x14,
	REANIM_ZOMBIE = 0x15,
	REANIM_SUN = 0x16,
	REANIM_POTATOMINE = 0x17,
	REANIM_SPIKEWEED = 0x18,
	REANIM_SPIKEROCK = 0x19,
	REANIM_THREEPEATER = 0x1A,
	REANIM_MARIGOLD = 0x1B,
	REANIM_ICESHROOM = 0x1C,
	REANIM_ZOMBIE_FOOTBALL = 0x1D,
	REANIM_ZOMBIE_NEWSPAPER = 0x1E,
	REANIM_ZOMBIE_ZAMBONI = 0x1F,
	REANIM_SPLASH = 0x20,
	REANIM_JALAPENO = 0x21,
	REANIM_JALAPENO_FIRE = 0x22,
	REANIM_COIN_SILVER = 0x23,
	REANIM_ZOMBIE_CHARRED = 0x24,
	REANIM_ZOMBIE_CHARRED_IMP = 0x25,
	REANIM_ZOMBIE_CHARRED_DIGGER = 0x26,
	REANIM_ZOMBIE_CHARRED_ZAMBONI = 0x27,
	REANIM_ZOMBIE_CHARRED_CATAPULT = 0x28,
	REANIM_ZOMBIE_CHARRED_GARGANTUAR = 0x29,
	REANIM_SCRAREYSHROOM = 0x2A,
	REANIM_PUMPKIN = 0x2B,
	REANIM_PLANTERN = 0x2C,
	REANIM_TORCHWOOD = 0x2D,
	REANIM_SPLITPEA = 0x2E,
	REANIM_SEASHROOM = 0x2F,
	REANIM_BLOVER = 0x30,
	REANIM_FLOWER_POT = 0x31,
	REANIM_CACTUS = 0x32,
	REANIM_DANCER = 0x33,
	REANIM_TANGLEKELP = 0x34,
	REANIM_STARFRUIT = 0x35,
	REANIM_POLEVAULTER = 0x36,
	REANIM_BALLOON = 0x37,
	REANIM_GARGANTUAR = 0x38,
	REANIM_IMP = 0x39,
	REANIM_DIGGER = 0x3A,
	REANIM_DIGGER_DIRT = 0x3B,
	REANIM_ZOMBIE_DOLPHINRIDER = 0x3C,
	REANIM_POGO = 0x3D,
	REANIM_BACKUP_DANCER = 0x3E,
	REANIM_BOBSLED = 0x3F,
	REANIM_JACKINTHEBOX = 0x40,
	REANIM_SNORKEL = 0x41,
	REANIM_BUNGEE = 0x42,
	REANIM_CATAPULT = 0x43,
	REANIM_LADDER = 0x44,
	REANIM_PUFF = 0x45,
	REANIM_SLEEPING = 0x46,
	REANIM_GRAVE_BUSTER = 0x47,
	REANIM_ZOMBIES_WON = 0x48,
	REANIM_MAGNETSHROOM = 0x49,
	REANIM_BOSS = 0x4A,
	REANIM_CABBAGEPULT = 0x4B,
	REANIM_KERNELPULT = 0x4C,
	REANIM_MELONPULT = 0x4D,
	REANIM_COFFEEBEAN = 0x4E,
	REANIM_UMBRELLALEAF = 0x4F,
	REANIM_GATLINGPEA = 0x50,
	REANIM_CATTAIL = 0x51,
	REANIM_GLOOMSHROOM = 0x52,
	REANIM_BOSS_ICEBALL = 0x53,
	REANIM_BOSS_FIREBALL = 0x54,
	REANIM_COBCANNON = 0x55,
	REANIM_GARLIC = 0x56,
	REANIM_GOLD_MAGNET = 0x57,
	REANIM_WINTER_MELON = 0x58,
	REANIM_TWIN_SUNFLOWER = 0x59,
	REANIM_POOL_CLEANER = 0x5A,
	REANIM_ROOF_CLEANER = 0x5B,
	REANIM_FIRE_PEA = 0x5C,
	REANIM_IMITATER = 0x5D,
	REANIM_YETI = 0x5E,
	REANIM_BOSS_DRIVER = 0x5F,
	REANIM_LAWN_MOWERED_ZOMBIE = 0x60,
	REANIM_CRAZY_DAVE = 0x61,
	REANIM_TEXT_FADE_ON = 0x62,
	REANIM_HAMMER = 0x63,
	REANIM_SLOT_MACHINE_HANDLE = 0x64,
	REANIM_CREDITS_FOOTBALL = 0x65,
	REANIM_CREDITS_JACKBOX = 0x66,
	REANIM_SELECTOR_SCREEN = 0x67,
	REANIM_PORTAL_CIRCLE = 0x68,
	REANIM_PORTAL_SQUARE = 0x69,
	REANIM_ZENGARDEN_SPROUT = 0x6A,
	REANIM_ZENGARDEN_WATERINGCAN = 0x6B,
	REANIM_ZENGARDEN_FERTILIZER = 0x6C,
	REANIM_ZENGARDEN_BUGSPRAY = 0x6D,
	REANIM_ZENGARDEN_PHONOGRAPH = 0x6E,
	REANIM_DIAMOND = 0x6F,
	REANIM_ZOMBIE_HAND = 0x70,
	REANIM_STINKY = 0x71,
	REANIM_RAKE = 0x72,
	REANIM_RAIN_CIRCLE = 0x73,
	REANIM_RAIN_SPLASH = 0x74,
	REANIM_ZOMBIE_SURPRISE = 0x75,
	REANIM_COIN_GOLD = 0x76,
	REANIM_TREE_OF_WISDOM = 0x77,
	REANIM_TREE_OF_WISDOM_CLOUDS = 0x78,
	REANIM_TREE_FOOD = 0x79,
	REANIM_CREDITS_MAIN = 0x7A,
	REANIM_CREDITS_MAIN2 = 0x7B,
	REANIM_CREDITS_MAIN3 = 0x7C,
	REANIM_ZOMBIE_CREDITS_DANCE = 0x7D,
	REANIM_CREDITS_STAGE = 0x7E,
	REANIM_CREDITS_BIGBRAIN = 0x7F,
	REANIM_CREDITS_FLOWER_PETALS = 0x80,
	REANIM_CREDITS_INFANTRY = 0x81,
	REANIM_CREDITS_THROAT = 0x82,
	REANIM_CREDITS_CRAZYDAVE = 0x83,
	REANIM_CREDITS_BOSSDANCE = 0x84,
	REANIM_ZOMBIE_CREDITS_SCREEN_DOOR = 0x85,
	REANIM_ZOMBIE_CREDITS_CONEHEAD = 0x86,
	REANIM_CREDITS_ZOMBIEARMY1 = 0x87,
	REANIM_CREDITS_ZOMBIEARMY2 = 0x88,
	REANIM_CREDITS_TOMBSTONES = 0x89,
	REANIM_CREDITS_SOLARPOWER = 0x8A,
	REANIM_CREDITS_ANYHOUR = 0x8B,
	REANIM_CREDITS_WEARETHEUNDEAD = 0x8C,
	REANIM_CREDITS_DISCOLIGHTS = 0x8D,
	NUM_REANIMS = 0x8E
};
enum ReanimLoopType
{
	REANIM_LOOP = 0x0,
	REANIM_LOOP_FULL_LAST_FRAME = 0x1,
	REANIM_PLAY_ONCE = 0x2,
	REANIM_PLAY_ONCE_AND_HOLD = 0x3,
	REANIM_PLAY_ONCE_FULL_LAST_FRAME = 0x4,
	REANIM_PLAY_ONCE_FULL_LAST_FRAME_AND_HOLD = 0x5
};
enum FilterEffect
{
	FILTER_EFFECT_NONE = 0xFFFFFFFF,
	FILTER_EFFECT_WASHED_OUT = 0x0,
	FILTER_EFFECT_LESS_WASHED_OUT = 0x1,
	FILTER_EFFECT_WHITE = 0x2,
	NUM_FILTER_EFFECTS = 0x3
};
#pragma endregion

class Reanimation
{
public:
	ReanimationType ReanimationType;
	float AnimTime;
	float AnimRate;
	ReanimatorDefinition* Definition;
	ReanimLoopType LoopType;
	bool Dead;
	int FrameStart;
	int FrameCount;
	int FrameBasePose;
	Sexy::SexyTransform2D OverlayMatrix;
	Color ColorOverride;
	ReanimatorTrackInstance* TrackInstances;
	int LoopCount;
	ReanimationHolder* ReanimationHolder;
	bool IsAttachment;
	int RenderOrder;
	Color ExtraAdditiveColor;
	bool EnableExtraAdditiveDraw;
	Color ExtraOverlayColor;
	bool EnableExtraOverlayDraw;
	float LastFrameTime;
	FilterEffect FilterEffect;

	ReanimationID GetID()
	{
		return (ReanimationID)(DWORD)(this + 1);
	}
};