#pragma once

#include <Windows.h>
#include <corecrt_math_defines.h>
#include <iostream>
#include <filesystem>
#include <string>
#include <fstream>
#include <streambuf>
#include <stdio.h>
#include <iomanip>
#include <sstream>
#include <format>
#include <vector>
#include <thread>
#include <cmath>
#include <list>
#include <map>
#include <set>